### ISSUE TITLE
Stutter not found by gradle post revision dc9d1bf

### ISSUE THREAD

**Issue by alphor** [tadfisher/gradle2nix#1]
First off, this looks like a great attempt! From looking at the code there isn't anything too complicated: get a project connection, build the model from there, map it to some json, and read that into Nix at nix build time.

When demoing this project for myself I ran into an issue building:
```
{ pkgs ? import <nixpkgs> {} }:

let
  fetchgit = pkgs.fetchgit;
  workingRevision = {
    rev = "dc9d1bfda6f3d590a8353a89dfb86608a7fb2b6b";
    sha256 = "0hyfa750d7mfgwb34vch9nqdha1dkpw16nnsxignrn92wb40z6h2";
  };
  notWorkingRevision = {
    rev = "13a84d7518f95b2fafc56713706e3ee9372f028c";
    sha256 = "0skahn25c5wjycsdd5vnnxz96i6dx2mv2sxzxgpz38darr54gg41";
  };
  src = fetchgit ({
    url = "https://github.com/tadfisher/gradle2nix";
  } // notWorkingRevision);
in import "${src}/default.nix" { inherit pkgs; }
```

stacktrace of the non working revision:
```
these derivations will be built:
  /nix/store/wj71sih4jm5d5ak2ahsqdvnwl534ygsb-gradle2nix-1.0.drv
building '/nix/store/wj71sih4jm5d5ak2ahsqdvnwl534ygsb-gradle2nix-1.0.drv'...
unpacking sources
unpacking source archive /nix/store/qnajpf1azg08p8dvrwccgizsim3qc7c8-p960i9p1hjks4q1jm0gv13vjbfv78vdr-gradle2nix-13a84d7
source root is p960i9p1hjks4q1jm0gv13vjbfv78vdr-gradle2nix-13a84d7
patching sources
configuring
no configure script, doing nothing
building
Initialized native services in: /build/tmp.gTX7QpRvTz/native

Welcome to Gradle 5.4.1!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4.1/release-notes.html

Using 4 worker leases.
Starting Build
Compiling initialization script '/nix/store/w4plz7cijp0b8p60dg9gby300anm48fs-init.gradle' using SubsetScriptTransformer.
Compiling initialization script '/nix/store/w4plz7cijp0b8p60dg9gby300anm48fs-init.gradle' using BuildScriptTransformer.
Generating /build/tmp.gTX7QpRvTz/caches/5.4.1/generated-gradle-jars/gradle-api-5.4.1.jar
w: /tmp/gradle-kotlin-dsl-extensions-5.4633021468261801480416525059466775102301jar/org/gradle/kotlin/dsl/GradleApiKotlinDslExtensions23.kt:39:47: 'VariantTransform' is deprecated. Deprecated in Java
w: /tmp/gradle-kotlin-dsl-extensions-5.4633021468261801480416525059466775102301jar/org/gradle/kotlin/dsl/GradleApiKotlinDslExtensions23.kt:39:153: 'ArtifactTransform' is deprecated. Deprecated in Java
w: /tmp/gradle-kotlin-dsl-extensions-5.4633021468261801480416525059466775102301jar/org/gradle/kotlin/dsl/GradleApiKotlinDslExtensions23.kt:49:47: 'VariantTransform' is deprecated. Deprecated in Java
w: /tmp/gradle-kotlin-dsl-extensions-5.4633021468261801480416525059466775102301jar/org/gradle/kotlin/dsl/GradleApiKotlinDslExtensions23.kt:49:153: 'ArtifactTransform' is deprecated. Deprecated in Java
Settings evaluated using settings file '/build/p960i9p1hjks4q1jm0gv13vjbfv78vdr-gradle2nix-13a84d7/settings.gradle.kts'.
Projects loaded. Root project using build file '/build/p960i9p1hjks4q1jm0gv13vjbfv78vdr-gradle2nix-13a84d7/build.gradle.kts'.
Included projects: [root project 'p960i9p1hjks4q1jm0gv13vjbfv78vdr-gradle2nix-13a84d7', project ':app', project ':model', project ':plugin']

> Configure project :
Evaluating root project 'p960i9p1hjks4q1jm0gv13vjbfv78vdr-gradle2nix-13a84d7' using build file '/build/p960i9p1hjks4q1jm0gv13vjbfv78vdr-gradle2nix-13a84d7/build.gradle.kts'.

FAILURE: Build failed with an exception.

* Where:
Build file '/build/p960i9p1hjks4q1jm0gv13vjbfv78vdr-gradle2nix-13a84d7/build.gradle.kts' line: 1

* What went wrong:
Plugin [id: 'org.ajoberstar.stutter', version: '0.5.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.ajoberstar.stutter:org.ajoberstar.stutter.gradle.plugin:0.5.0')
  Searched in the following repositories:
    maven(file:/nix/store/lskhp3s0wzzbxk7d5dyngih1xv2j1mb2-gradle-env---plugins/)

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.ajoberstar.stutter', version: '0.5.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.ajoberstar.stutter:org.ajoberstar.stutter.gradle.plugin:0.5.0')
  Searched in the following repositories:
    maven(file:/nix/store/lskhp3s0wzzbxk7d5dyngih1xv2j1mb2-gradle-env---plugins/)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:262)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$100(DefaultPluginRequestApplicator.java:63)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:91)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1.transform(DefaultPluginRequestApplicator.java:88)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:205)
        at org.gradle.util.CollectionUtils.collect(CollectionUtils.java:200)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:88)
        at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:49)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:190)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:364)
        at Program.execute(Unknown Source)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:506)
        at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:206)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:114)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:51)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:36)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:34)
        at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:63)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:63)
        at org.gradle.configuration.project.BuildScriptProcessor$1.run(BuildScriptProcessor.java:44)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:200)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:186)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject$1.run(LifecycleProjectEvaluator.java:106)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:183)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withProjectLock(DefaultProjectStateRegistry.java:226)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:220)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:186)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:95)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:67)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:695)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:143)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:302)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:210)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:134)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:58)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:55)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:82)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:75)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:183)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:75)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:55)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:58)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:49)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:55)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:208)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:394)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:367)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:37)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:23)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:360)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:292)
        at org.gradle.launcher.Main.doAction(Main.java:36)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)


* Get more help at https://help.gradle.org

BUILD FAILED in 29s
builder for '/nix/store/wj71sih4jm5d5ak2ahsqdvnwl534ygsb-gradle2nix-1.0.drv' failed with exit code 1
error: build of '/nix/store/wj71sih4jm5d5ak2ahsqdvnwl534ygsb-gradle2nix-1.0.drv' failed
```

Revision 13a84 adds the stutter dependency as a gradle plugin, but it looks like it's added in 987c03604bc7a8edcf51805c64ec8469e0afc65a in the json file, though I can't get that to build either.

I'm wondering if any of these commits after dc9d1bf build for you?

Also, after building that commit all I can see is a gradle wrapper-esque file called gradle2nix in `./bin`. I'm not sure if that's expected or usage is different.

**Comment by tadfisher** [comment]
First off, thanks for trying this out!

This is currently in a state of flux; the dependency JSON format is all-new, but I haven't finished the actual Nix derivation which consumes it. For now, the project should be buildable with `java` in the environment, using `./gradlew build`.

I was hoping to get some feedback into how this should be structured; do we want to generate a `default.nix`, or something like a `gradle-env.nix` which is imported if you want?

**Comment by tadfisher** [comment]
@alphor Care to try the latest commit? It should be self-hosting now.

For now, to use this you'll need to write your own build script and import the generated `gradle-env.nix`. See `default.nix` for details.

**Comment by alphor** [comment]
Here's the derivation I wrote, following the comments you left modulo some typos (gradleEnv.nix -> gradle-env.nix, omission of name in derivation)
``` nix
{ pkgs ? import <nixpkgs> {} }:

let
  src = pkgs.fetchgit {
    url = "https://github.com/tadfisher/gradle2nix";
    rev = "e0ebecec21d1895ac7ea1bafa3261ad5f29e7ae6";
    sha256 = "1pgk8lk0si8ckrbd5b0kcar62a0iq1ja0nk87ra86vmaaznzwn1v";
};
   buildGradle = pkgs.callPackage "${src}/gradle-env.nix" {};
in 
buildGradle {
  name = "gradle2nix";
  envSpec = "${src}/gradle-env.json";
  inherit src;
  gradleFlags = [ "installDist" ];

  installPhase = ''
    mkdir -p $out
    cp -r app/build/install/gradle2nix $out
  '';
}
```
It worked to build, and gradle2nix in bin is executable, though I couldn't get it to show up in my path when I put it in `environment.systemPackages` with `(import ./g2n.nix { inherit pkgs; }`. Calling through to the generated result symlink works, though.
Things I have tried:
- building a gradle-example project running 4.3.1, 4.6, and 5.4.1. These all failed because:
`Exception in thread "main" org.gradle.tooling.BuildException: Could not fetch model of type 'Build' using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.3.1-all.zip'.`
- building the KotlinLanguageServer (using gradle 4.6), this actually generated gradle-env.nix, gradle-env.json which suggests that maybe it's just my internet connection being unfortunate, I would be very surprised if this was because the example project does something the KotlinLanguageServer does not. If I get time to head to the library tomorrow, I will try again there.

**Comment by alphor** [comment]
Would you like pull requests on this repo?

**Comment by tadfisher** [comment]
> I couldn't get it to show up in my path when I put it in environment.systemPackages with `(import ./g2n.nix { inherit pkgs; }`

I have no idea why this would be the case, but I'll try it out here and see what the problem is.

> building a gradle-example project running 4.3.1, 4.6, and 5.4.1. These all failed

This is a problem I'm seeing:

```
org.gradle.tooling.BuildException: Could not fetch model of type 'Build' using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.3.1-all.zip
```

For now, the lowest Gradle version supported is 4.4.1, because plugin resolution works much differently prior to that version and I haven't written an alternative plugin resolver.

However, if it's failing on 4.6 and 5.4.1, I'd like to see the project so I can find out what's failing.

> Would you like pull requests on this repo?

Yes, that's fine.

**Comment by alphor** [comment]
Yeah, no problem!

I'm going to close this issue since it's resolved and create a new one: mainly gradle2nix isn't in the path (but does produce working output) when I provide it in environment.systemPackages using the expression in this comment: https://github.com/tadfisher/gradle2nix/issues/1#issuecomment-504620088

**Comment by alphor** [comment]
Figured it out actually: was missing the glob in the installPhase: `cp -r app/build/install/gradle2nix/* $out`
